name: Build and Deploy Strapi App

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Cache node modules
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm install

      - name: Create .env file
        run: |
          touch .env
          echo HOST = ${{ secrets.HOST }} >> .env
          echo PORT = ${{ secrets.PORT }} >> .env
          echo URL = ${{ secrets.URL }} >> .env
          echo APP_KEYS = ${{ secrets.APP_KEYS }} >> .env
          echo API_TOKEN_SALT = ${{ secrets.API_TOKEN_SALT }} >> .env
          echo TRANSFER_TOKEN_SALT = ${{ secrets.TRANSFER_TOKEN_SALT }} >> .env
          echo DATABASE_CLIENT = ${{ secrets.DATABASE_CLIENT }} >> .env
          echo DATABASE_SSL = ${{ secrets.DATABASE_SSL }} >> .env
          echo DATABASE_FILENAME = ${{ secrets.DATABASE_FILENAME }} >> .env
          echo JWT_SECRET = ${{ secrets.JWT_SECRET }} >> .env

      - name: Build Angular app
        run: npm run build --omit=dev

      - name: Transfer to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          source: dist/*
          target: /home/goldrush-backend
